# Generated by Selenium IDE
# permitir mandar por gmail: https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4M2DM7kvnClCJpPbPMFWq1-wguEnDPfyTr0RAFMnkDnVxitkun-r2GquqVmn5q-NLRtzKW7YYASu4yutswKjOM5Xtwlvw
from datetime import date
from parsel import Selector
import pandas as pd
import xlsxwriter
import re
import os
#import pytest
import numpy as np
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from win32com.client import Dispatch #Solo para windows

correo = 'indecopicem@hotmail.com'
contra = 'Indecopi2020'
#url = 'https://onedrive.live.com/?id=5E961F0F4F0BA0D7%21107&cid=5E961F0F4F0BA0D7'
path = r"C:\Users\Andrés\AppData\Local\Programs\Python\Python38\Lib\site-packages\selenium\chromedriver.exe"

class one_drive_api:
    
    def __init__(self,correo,contra,driver_path):
        self.correo = correo
        self.contra = contra
        self.driver_path = driver_path
        options = webdriver.ChromeOptions()
        options.add_argument("--start-maximized")
        self.driver = webdriver.Chrome(self.driver_path, chrome_options=options)
    
    def inicia_sesion(self):
        # Entra e inicia sesión
        print('Iniciando sesión')
        self.driver.get("https://onedrive.live.com/about/es-es/signin/")
        time.sleep(15)
       # self.driver.get("https://onedrive.live.com/")
       # time.sleep(10)
       # self.driver.find_element(By.XPATH, "//button[contains(@class,'c-glyph glyph-cancel')]").click()
       # self.driver.find_element(By.LINK_TEXT, "Iniciar sesión").click()
       # time.sleep(5)
       # window_after = self.driver.window_handles[1]
       # self.driver.switch_to_window(window_after)
        self.driver.switch_to.frame(1)
        time.sleep(15)
        self.driver.find_element_by_class_name('form-control').send_keys(self.correo)
        self.driver.find_element_by_class_name('form-control').send_keys(Keys.ENTER)
        time.sleep(15)
        self.driver.find_element(By.ID, "i0118").send_keys(self.contra)
        time.sleep(10)
        self.driver.find_element(By.ID, "idSIButton9").click()
        time.sleep(5)
        print('Sesión iniciada con éxito')

    def descarga_archivo(self,url,pat,espera=300):    
        # Direccionar al url de archivos
        self.driver.get(url)       
        time.sleep(20)

        if isinstance(pat,type(list)):
            print('Iniciando Descarga de ', len(pat), 'archivos, recuerde ser específico :)')
            cajas = []
            
            for i in range(0,len(pat)):
                caja = self.driver.find_element(By.XPATH,'//div[contains(@data-automationid,"' + str(pat[i]) + '")]/span[contains(@role,"checkbox")]')
                cajas.append(caja)
            
            for i in range(0,len(cajas)):
                cajas[i].click()
            
        else:
            print('Iniciando Descarga de los archivos que cumplan con el patrón, puede fallar si son más de 25 archivos en la carpeta')
            cajas = self.driver.find_elements(By.XPATH,'//div[contains(@data-automationid,"' + str(pat) + '")]/span[contains(@role,"checkbox")]')
            for i in range(0,len(cajas)):
                cajas[i].click()
            
            time.sleep(3)
            
        # Descarga archivos       
        self.driver.find_element(By.XPATH, "//i[contains(@data-icon-name,'Download')]").click()
        time.sleep(espera)
        print("Descarga Completa")

    def descarga_carpeta(self,url,nombre,espera=300):    
        # Direccionar al url de archivos
        self.driver.get(url)
        time.sleep(10)
        print("Iniciando Descarga")
        self.driver.find_element(By.XPATH,'//div[contains(@data-automationid,"'+ nombre + '")]/span[contains(@role,"checkbox")]').click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, "//i[contains(@data-icon-name,'Download')]").click()
        time.sleep(espera)
        print("Descarga Completa")


    def subir_archivo(self,url,archivo,espera=90):
        # Direccionar al url donde subir archivos
        print("Subiendo archivo: ",archivo)
        self.driver.get(url)
        time.sleep(10)
        
        # Subir archivos
        self.driver.find_element(By.XPATH, "//i[contains(@data-icon-name,'Upload')]").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@type='file']").send_keys(archivo)
        time.sleep(3)
        try:
            self.driver.find_element_by_xpath("//button[contains(@class,'od-Button OperationMonitor-itemButtonAction')]").click()
        except:
            pass
        time.sleep(espera)
        print("Archivo subido con éxito")
        
    def cerrar_sesion(self):
        print("Cerrando sesión")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_2KqWkae0FcyhdNhWQ-Cp-M > img").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "mectrl_body_signOut").click()
        time.sleep(5)
        self.driver.quit()
        print("Sesión cerrada con éxito, gracias por usar esta API")
        
s = one_drive_api(correo, contra, path)
s.inicia_sesion()
#s.descarga_archivo('https://onedrive.live.com/?id=C271252EA0CD8FDC%21113&cid=C271252EA0CD8FDC','_d')
s.descarga_archivo('https://onedrive.live.com/?id=5E961F0F4F0BA0D7%21107&cid=5E961F0F4F0BA0D7','informe',30)
s.descarga_archivo('https://onedrive.live.com/?id=5E961F0F4F0BA0D7%21107&cid=5E961F0F4F0BA0D7',['informe limpio del 2021-02-02.xlsx','informe limpio del 2021-02-03.xlsx'])
s.descarga_archivo('https://onedrive.live.com/?id=5E961F0F4F0BA0D7%21107&cid=5E961F0F4F0BA0D7','.xlsx')

url_raiz = 'https://onedrive.live.com/?id=root&cid=5E961F0F4F0BA0D7'
s.descarga_carpeta(url_raiz,"Quantico-informes_diarios")

url = 'https://onedrive.live.com/?id=5E961F0F4F0BA0D7%21106&cid=5E961F0F4F0BA0D7'
archivo = r"C:\Users\IDEAPAD530S\data_todo.dta"

s.subir_archivo(url,archivo)

s.cerrar_sesion()

